# permissions for end users to edit nameclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nameclass-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demo
    app.kubernetes.io/part-of: demo
    app.kubernetes.io/managed-by: kustomize
  name: nameclass-editor-role
rules:
- apiGroups:
  - demo.demo.com
  resources:
  - nameclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.demo.com
  resources:
  - nameclasses/status
  verbs:
  - get
