---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - demo.demo.com
  resources:
  - nameclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.demo.com
  resources:
  - nameclasses/finalizers
  verbs:
  - update
- apiGroups:
  - demo.demo.com
  resources:
  - nameclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - namesapceclass.demo.com
  resources:
  - namesapces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - namesapceclass.demo.com
  resources:
  - namesapces/finalizers
  verbs:
  - update
- apiGroups:
  - namesapceclass.demo.com
  resources:
  - namesapces/status
  verbs:
  - get
  - patch
  - update
